### ISSUE TITLE
yarn classic (1.x) fails with ESM error

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-backend#1009]
### Environment information

```plain text
(NOTE: this is part of the problem...)
(base) ➜  feb8-yarn-classic git:(main) npx amplify info 
/Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xss/repo/feb8-yarn-classic/node_modules/strip-ansi/index.js from /Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js not supported.
Instead change the require of /Users/xss/repo/feb8-yarn-classic/node_modules/strip-ansi/index.js in /Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js:2:19)
    at Object.<anonymous> (/Users/xss/repo/feb8-yarn-classic/node_modules/wrap-ansi/index.js:2:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.8.1
```

### Description

If using yarn classic (1.x) all `amplify` commands fail with ESM error.

Steps to repro:

```
yarn set version classic
yarn --version # Should be 1.x
yarn create next-app feb8-yarn-classic && cd feb8-yarn-classic
yarn create amplify
# To ensure classic yarn, check yarn.lock - should contain "# yarn lockfile v1" at the top. If not run `yarn set version classic && yarn install` and check again
yarn amplify sandbox
# Notice ESM error
```

The ESM error is as follows:

```
(base) ➜  feb8-yarn-classic git:(main) yarn amplify sandbox
yarn run v1.22.21
$ /Users/xss/repo/feb8-yarn-classic/node_modules/.bin/amplify sandbox
/Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xss/repo/feb8-yarn-classic/node_modules/strip-ansi/index.js from /Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js not supported.
Instead change the require of /Users/xss/repo/feb8-yarn-classic/node_modules/strip-ansi/index.js in /Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/xss/repo/feb8-yarn-classic/node_modules/string-width/index.js:2:19)
    at Object.<anonymous> (/Users/xss/repo/feb8-yarn-classic/node_modules/wrap-ansi/index.js:2:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.8.1
error Command failed with exit code 1.
```

I've observed this on both NodeJS v18 and v20.

I thought that ESM should be handled by the generated `amplify/package.json` file which has `"type": "module",` but perhaps not.

**Comment by ykethan** [comment]
@johnpc this is currently being tracked on https://github.com/aws-amplify/amplify-backend/issues/997

**Comment by 0618** [comment]
The error is because some of the dependencies of nextjs are outdated, it can be solved by adding some resolutions to the package.json file.

```
{
...
"resolutions": {"string-width": "^7", "wrap-ansi": "^9"}
...
}
```

**Comment by johnpc** [comment]
Confirmed that adding those resolutions fixes the build for a default nextjs app. However, I don't have to do anything like this for `yarn` v2+ or with `npm`.

Therefore this still feels like a limitation with amplify's compatibility with yarn 1.x. 

I worry yarn 1.x customers will bump up against this a lot.

**Comment by 0618** [comment]
Another work around is to delete yarn.lock and node_modules, then install.

```
yarn add create-amplify@beta
rm -rf yarn.lock node_modules
yarn install
yarn create-amplify
```

**Comment by 0618** [comment]
Another work around is, after `create next-app`, run `yarn upgrade`.
