### ISSUE TITLE
Deployment failed: MissingRequiredParameter: Missing required key 'functionId' in params

### ISSUE THREAD

**Issue by cabcookie** [aws-amplify/amplify-backend#1077]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 112.33 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: undefined - undefined
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.16
  aws-cdk: 2.126.0
  aws-cdk-lib: 2.126.0
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hello, I run into an issue with my sandbox environment. It happened twice to me in the last 2 weeks and I had to delete and recreate my sandbox which has been quite cumbersome (including recreation of demo data).
I login to my account using SSO and the profile org-data-amplify. My session is valid for a couple of hours and then I need to sign in again. Yesterday, I launched my sandbox environment with `npx amplify sandbox --profile org-data-amplify` and forgot to stop it. So, today I got back to VS Code (I didn't restart it) and stopped the sandbox and ran the command again. Now, I tried to make a change to my data model. I changed my Activity schema from
```javascript
const schema = a.schema({
  Context: a.enum(["family", "hobby", "work"]),
  Activity: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      finishedOn: a.datetime(),
    })
    .authorization([a.allow.owner()]),
});
```

to
```javascript
const schema = a.schema({
  Context: a.enum(["family", "hobby", "work"]),
  Activity: a
    .model({
      owner: a.string().authorization([a.allow.owner().to(["read", "delete"])]),
      notes: a.string(),
      slateNotes: a.string(),
      finishedOn: a.datetime(),
    })
    .authorization([a.allow.owner()]),
});
```

Amplify identified correctly a file update, synthesized the template and tried to deploy the update but then failed with the mentioned error message. Here is the output in my console:
[Sandbox] Triggered due to a file update event: /Users/carskoch/Development/personal-crm/amplify/data/resource.ts

✨  Synthesis time: 3.86s

⚠️ The --hotswap and --hotswap-fallback flags deliberately introduce CloudFormation drift to speed up deployments
⚠️ They should only be used for development - never use them for your production Stacks!

amplify-personalcrm-carskoch-sandbox-63e4bb09d0: deploying... [1/1]

✨ hotswapping resources:
   ✨ AWS::AppSync::FunctionConfiguration 'MutationcreateActivityauth0Function'
   ✨ AWS::AppSync::FunctionConfiguration 'MutationupdateActivityauth0Function'
   ✨ AWS::AppSync::GraphQLSchema 'uevvie4lgje2pegsontu5uvbwaGraphQLSchema'
   ✨ Contents of S3 Bucket 'amplify-personalcrm-carsk-amplifydataamplifycodege-8slq063fvosf'

✨ Contents of S3 Bucket 'amplify-personalcrm-carsk-amplifydataamplifycodege-8slq063fvosf' hotswapped!
✨ AWS::AppSync::GraphQLSchema 'uevvie4lgje2pegsontu5uvbwaGraphQLSchema' hotswapped!
The CloudFormation deployment has failed. Find more information in the CloudFormation AWS Console for this stack.
Caused By: ❌ Deployment failed: MissingRequiredParameter: Missing required key 'functionId' in params

It mentions I should verify CloudFormation. However, CloudFormation is not showing any events.
How can I fix this issue?

**Comment by cabcookie** [comment]
I ran `npx amplify sandbox` with the `--debug` option and received more details:
```
[DEBUG] 2024-02-27T13:05:14.681Z: 
 ❌  amplify-personalcrm-carskoch-sandbox-63e4bb09d0 failed: MissingRequiredParameter: Missing required key 'functionId' in params
    at ParamValidator.fail (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:224807)
    at ParamValidator.validateStructure (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:225157)
    at ParamValidator.validateMember (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:225789)
    at ParamValidator.validate2 [as validate] (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:224402)
    at Request.VALIDATE_PARAMETERS (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:143072)
    at Request.callListeners (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:91385)
    at callNextListener (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:91177)
    at /Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:141847
    at finish (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:125042)
    at /Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:125392 {
  code: 'MissingRequiredParameter',
  time: 2024-02-27T13:05:14.680Z
}

[DEBUG] 2024-02-27T13:05:14.681Z: 
 ❌ Deployment failed: MissingRequiredParameter: Missing required key 'functionId' in params
    at ParamValidator.fail (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:224807)
    at ParamValidator.validateStructure (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:225157)
    at ParamValidator.validateMember (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:225789)
    at ParamValidator.validate2 [as validate] (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:224402)
    at Request.VALIDATE_PARAMETERS (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:143072)
    at Request.callListeners (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:91385)
    at callNextListener (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:91177)
    at /Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:141847
    at finish (/Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:125042)
    at /Users/carskoch/Development/personal-crm/node_modules/aws-cdk/lib/index.js:373:125392 {
  code: 'MissingRequiredParameter',
  time: 2024-02-27T13:05:14.680Z
}
```

**Comment by ykethan** [comment]
Hey @cabcookie, could you try bumping the package version to beta which should contain the latest changes and re-run the sandbox.

```
"@aws-amplify/backend": "0.13.0-beta.3",
"@aws-amplify/backend-cli": "0.12.0-beta.3",
```

**Comment by cabcookie** [comment]
As I seem to have a working sandbox I compared the 2 `amplifyconfiguration.json` files and the main differences between the 2 were how the enums were treated.

When comparing the 2 configuration files, these are the differences (comparing the failing configuration to the working configuration):

**Deleted:**
- modelIntrospection.models.Activity.fields.noteVersion `// obviously as I added it for this test`
- modelIntrospection.enums.SixWeekBatchStatus
- modelIntrospection.enums.SixWeekBatchAppetite

**Updated:**
- aws_user_pools_id:  `// obvious`
- aws_user_pools_web_client_id:  `// obvious`
- aws_appsync_graphqlEndpoint:   `// obvious`
- modelIntrospection.models.SixWeekBatch.fields.status.type.enum: "SixWeekBatchStatus" to "Status"
- modelIntrospection.models.SixWeekBatch.fields.appetite.type.enum: "SixWeekBatchAppetite" to "Appetite"

**Added:**
- modelIntrospection.enums.Status
- modelIntrospection.enums.Appetite

I guess this is because of the "failing" configuration has been created with a previous version, and the new sandbox has been created using these versions:
```
@aws-amplify/backend: 0.12.1
@aws-amplify/backend-cli: 0.11.1
```

I have no idea if this impacts the behaviour and causing the problem though
