### ISSUE TITLE
Amplify Gen 2 - Lambda Resolver Breaks When timeoutSeconds or memoryMB set

### ISSUE THREAD

**Issue by alexwhb** [aws-amplify/amplify-backend#1114]
### Environment information

```plain text
System:
  OS: macOS 14.3.1
  CPU: (16) arm64 Apple M3 Max
  Memory: 328.11 MB / 48.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn: undefined - undefined
  npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.4
  @aws-amplify/backend-cli: 0.12.0-beta.4
  aws-amplify: 6.0.19
  aws-cdk: 2.127.0
  aws-cdk-lib: 2.127.0
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Any time I change my lambda functions runtime or memoryMB values my lambda throws this error: 

```
{
    "errorType": "Error",
    "errorMessage": "No context value present for amplify-backend-namespace key",
    "stack": [
        "Error: No context value present for amplify-backend-namespace key",
        "    at _Node.getContext (file:///var/task/index.mjs:356:17)",
        "    at getBackendIdentifier (file:///var/task/index.mjs:431952:39)",
        "    at createDefaultStack (file:///var/task/index.mjs:432251:72)",
        "    at new BackendFactory (file:///var/task/index.mjs:432392:43)",
        "    at defineBackend (file:///var/task/index.mjs:432438:20)",
        "    at file:///var/task/index.mjs:433367:15"
    ]
}
```

here's my resource def: 
```ts
import {defineFunction, secret} from '@aws-amplify/backend';

export const loginMutation = defineFunction({
    timeoutSeconds: 60,
    memoryMB: 256
});
```

if I just export: 
```ts 
export const loginMutation = defineFunction({});
```
My function works. 

Just for some added context I think the error is being thrown from this code: 
```js
      /**
       * Retrieves a value from tree context if present. Otherwise, would throw an error.
       *
       * Context is usually initialized at the root, but can be overridden at any point in the tree.
       *
       * @param key The context key
       * @returns The context value or throws error if there is no context value for this key
       */
      getContext(key) {
        const value = this._context[key];
        if (value !== void 0) {
          return value;
        }
        if (value === void 0 && !this.scope?.node) {
          throw new Error(`No context value present for ${key} key`);
        }
        return this.scope && this.scope.node.getContext(key);
      }
```

any thoughts or advice on how to solve this let me know.

**Comment by edwardfoyle** [comment]
Hi @alexwhb, so far I am unable to reproduce this. Are you using `npx amplify sandbox` or `npx amplify pipeline-deploy` to deploy the backend?

**Comment by alexwhb** [comment]
@edwardfoyle hey, thanks for looking into it. im using npx sandbox.

**Comment by edwardfoyle** [comment]
Taking a closer look at your stack trace, it looks like you might be running the library in some sort of bundled context? eg The stack trace shows things like `file:///var/task/index.mjs:432438:20`. Can you share more about how you have installed / built the `@aws-amplify/backend` package and how you're executing the CLI?

**Comment by alexwhb** [comment]
@edwardfoyle Ya absolutely. So I'm building a service that connects to shopify. This particular Lambda logs into Shopify using a customers user name and password, which ideally will populate a dynomoDB table with some info related to the user: 

```ts 
import type {AppSyncResolverHandler} from "aws-lambda";
import {ResolverContext} from "../auth/handler";
import {z} from "zod";
import {getShopifyClient} from "../../utils/shopify-utils";
import {createStorefrontApiClient} from "@shopify/storefront-api-client";
import {createHash} from 'crypto';
// import {docClient} from "../../utils/dynomo-utils";
// import {UserTableName} from "../../utils/backend-utils";
// import {GetCommand, PutCommand} from "@aws-sdk/lib-dynamodb";
import {v4 as uuidv4} from 'uuid';
import {validateInput} from "../../utils/input-validation";


export const handler: AppSyncResolverHandler<
    ResolverArgs,
    ResolverResult
> = async (event, context) => {

    // TODO I need to figure out how I can pass in the app code in here since this should be an unauthorized route.
    const customContext = context.clientContext?.Custom as ResolverContext

    console.log(context)
    console.log(event)

    // this is our salt.
    const appCode = "SOME_CODE" // todo update this to be dynamic

    const schema =
        z.object({
            username: z.string().email(),
            password: z.string()
                .min(5)
                .max(40)
        })

    validateInput(schema, event.arguments)

    // todo figure out where to get store code header from
    const client = getShopifyClient(appCode)
    const accessToken = await getAccessToken(client, event.arguments.username, event.arguments.password)
    const customerData = await getCustomerInfo(client, accessToken)
    // const userID = sha256(`${customerData.customer.id}${appCode}`)
    // const sessionId = await createOrUpdateUser(userID, appCode);

    return {id: customerData.customer.id, sessionId: 'test121212', email: customerData.customer.email}
};



async function getCustomerInfo(client: ReturnType<typeof createStorefrontApiClient>, accessToken: string): Promise<CustomerResponse> {
    const {data, errors, extensions} = await client.request<CustomerResponse>(customerQuery, {
        variables: {
            customerAccessToken: accessToken
        },
    });

    if (errors || data == undefined) {
        console.error(errors)
        throw Error(`Error logging user in: ${JSON.stringify(errors)}`) // todo this should have a code so we can check on the app side
    }

    return data
}


async function getAccessToken(client: ReturnType<typeof createStorefrontApiClient>, username: string, password: string): Promise<string> {
    const {data, errors, extensions} = await client.request<CustomerAccessTokenCreateResponse>(loginMutation, {
        variables: {
            input: {
                email: username,
                password: password
            }
        },
    });

    if (errors || data == undefined) {
        console.error(errors)
        throw Error(`Error logging user in ${JSON.stringify(errors)}`) // todo this should have a code so we can check on the app side
    }

    return data.customerAccessTokenCreate.customerAccessToken.accessToken
}
```

note I've commented out my DynomoDB imports. Those may have been causing issues. But I will say even with them commented out, when I change the timeout and lambda RAM values I get that error, so I'm not really sure what's up.

**Comment by edwardfoyle** [comment]
Hmm, I'm still not seeing anything out of place. I wonder if you have an older version of the CLI in your package lock? Can you try running `npm install -D @aws-amplify/backend-cli@beta @aws-amplify/backend@beta` to ensure you've got the latest beta version of those packages?

**Comment by alexwhb** [comment]
@edwardfoyle I think I got it!!! 🎉 Your suggestion on the package lock made me think maybe something node related got out of sync... So I deleted  my node_module, my package lock, and my .amplify file and re set everything. Seems to be working now! I think there must have been a dependency that was not correct or something. I so appreciate your help.

**Comment by alexwhb** [comment]
I'm re-opening this issue. So This lambda works no problem until I import and setup AWS SDK V3 for dynamodb. As soon as I do that I get this same error again. I think I can use the V2 API just fine. I've done it in the past, but I'm trying to move everything into using the V3 API to stay away from a deprecated or soon to be deprecated system.

**Comment by fossamagna** [comment]
@alexwhb @edwardfoyle 
Perhaps the following import may be the cause.
```ts
import {UserTableName} from "../../utils/backend-utils";
```

If you have defined UserTableName in `backend-utils.ts` as follows. The backend.ts gets bundled into the code that is deployed to the lambda and an error occurs when the lambda is called.
```ts
import { backend } from "../backend";

export const todoTableName = backend.data.resources.tables["Todo"].tableName;
```

I think it is better to specify the name of the DynamoDB table in an environment variable. But now, as per https://github.com/aws-amplify/amplify-category-api/issues/2217, there seems to be a problem to get the DynamoDB table for the schema defined in defineData.

**Comment by edwardfoyle** [comment]
Ah, that's a good call. And yes that would definitely cause the problem you are seeing. The backend definition in the `amplify` folder cannot be referenced in lambda handler code.

If you are trying to read/write to a table that is created as part of your GraphQL data model, we recommend accessing the table from your lambda via the GraphQL API. You can read about how to configure the lambda to have access to your API [here](https://docs.amplify.aws/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/).

**Comment by alexwhb** [comment]
@fossamagna your absolutely right this was the issue. Sorry for the late reply. Removing this code solved the problem. 🙌🎉 

Thanks so much for the help
