### ISSUE TITLE
[CICD] Windows run_e2e_tests failure with "The process <PID> not found."

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-backend#1157]
### Environment information

```plain text
N/A
```

### Description

Sample run: https://github.com/aws-amplify/amplify-backend/actions/runs/8296818251/job/22706699128?pr=1143#step:8:1621
```log
test at file:\D:\a\amplify-backend\amplify-backend\packages\integration-tests\lib\test-e2e\deployment.test.js:87:26
✖ [typescript-idiom] deploys fully (97357.9754ms)
  Error: Command failed with exit code 128: taskkill /pid 7100 /f /t
  ERROR: The process "7100" not found.
      at makeError (file:///D:/a/amplify-backend/amplify-backend/node_modules/execa/lib/error.js:60:11)
      at handlePromise (file:///D:/a/amplify-backend/amplify-backend/node_modules/execa/index.js:124:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at killExecaProcess (D:\a\amplify-backend\amplify-backend\packages\integration-tests\src\process-controller\execa_process_killer.ts:18:5)
      at ProcessController.run (D:\a\amplify-backend\amplify-backend\packages\integration-tests\src\process-controller\process_controller.ts:100:9)
      at MinimalWithTypescriptIdiomTestProject.deploy (D:\a\amplify-backend\amplify-backend\packages\integration-tests\src\test-project-setup\test_project_base.ts:69:7)
      at TestContext.<anonymous> (D:\a\amplify-backend\amplify-backend\packages\integration-tests\src\test-e2e\deployment.test.ts:133:13)
      at async Test.run (node:internal/test_runner/test:632:9)
      at async Promise.all (index 0)
      at async Suite.run (node:internal/test_runner/test:948:7) {
    shortMessage: 'Command failed with exit code 128: taskkill /pid 7100 /f /t',
    command: 'taskkill /pid 7100 /f /t',
    escapedCommand: 'taskkill "/pid" 7100 "/f" "/t"',
    exitCode: 128,
    signal: undefined,
    signalDescription: undefined,
    stdout: '',
    stderr: 'ERROR: The process "7100" not found.',
    cwd: 'D:\\a\\amplify-backend\\amplify-backend',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
```

**Comment by rtpascual** [comment]
Another run: https://github.com/aws-amplify/amplify-backend/actions/runs/8367027538/job/22908622483?pr=1178#step:8:2185

**Comment by rtpascual** [comment]
Addressed by https://github.com/aws-amplify/amplify-backend/pull/2154
