### ISSUE TITLE
Data API throws error (instead of passing in error object) when attempting to retrieve a deleted hasOne() Item

### ISSUE THREAD

**Issue by AakashKB** [aws-amplify/amplify-backend#1243]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 316.88 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  pnpm: 8.10.5 - /usr/local/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.14
  @aws-amplify/backend-cli: 0.12.0-beta.16
  aws-amplify: 6.0.20
  aws-cdk: 2.133.0
  aws-cdk-lib: 2.133.0
  typescript: 5.4.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables%
```

### Description

Schema:
```
 PlayerCharacterRelationship: a
            .model({
                user: a.belongsTo("User"),
                npc: a.belongsTo("Character"),
                conversations: a.hasMany("Conversation"), //add relationship context
                lastConversation: a.hasOne("Conversation"),
                owner: a.string(),
            })
            .authorization([a.allow.owner(), a.allow.private()]),
```

Reproduce:
```
1. Create `PlayerCharacterRelationship`
2. Create `Conversation`
3. Add conversation to `PlayerCharacterRelationship` as `lastConversation`
4. Delete conversation
5. Get `PlayerCharacterRelationship` (No selection specified)
6. Get `lastConversation` from it via: 
    const { data: conversation, errors } = (await pcr.lastConversation()) || {};
```
Expected behavior:
`conversation` is empty or null, or errors caught and returned in `errors`

Actual behavior:
Error thrown:
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of null (reading 'id')",
    "stack": [
        "TypeError: Cannot read properties of null (reading 'id')",
        "    at file:///var/task/index.mjs:47136:45",
        "    at Array.map (<anonymous>)",
        "    at file:///var/task/index.mjs:47134:50",
        "    at Array.map (<anonymous>)",
        "    at initializeModel (file:///var/task/index.mjs:47035:17)",
        "    at _get (file:///var/task/index.mjs:47690:31)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async getCurrentConversation (file:///var/task/index.mjs:55806:42)",
        "    at async processMessages (file:///var/task/index.mjs:56155:38)",
        "    at async SpeechCompletion_default (file:///var/task/index.mjs:56194:7)"
    ]
}
```

**Comment by AakashKB** [comment]
Actually seems to be a larger issue of getting a similar error when trying to `get` any non-existent item from:

```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of null (reading 'id')",
    "stack": [
        "TypeError: Cannot read properties of null (reading 'id')",
        "    at file:///var/task/index.mjs:47136:45",
        "    at Array.map (<anonymous>)",
        "    at file:///var/task/index.mjs:47134:50",
        "    at Array.map (<anonymous>)",
        "    at initializeModel (file:///var/task/index.mjs:47035:17)",
        "    at _get (file:///var/task/index.mjs:47690:31)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async getPlayerCharacterRelationship (file:///var/task/index.mjs:55787:42)",
        "    at async processMessages (file:///var/task/index.mjs:56154:15)",
        "    at async SpeechCompletion_default (file:///var/task/index.mjs:56194:7)"
    ]
}
```

I would expect it to fail gracefully by returning `{ data: null | {}, errors: {...} }`

**Comment by ykethan** [comment]
Hey,👋 thanks for raising this! I'm going to transfer this over to our API repository for better assistance 🙂
