### ISSUE TITLE
An error occurs with "a.allow.resource(functionWithDataAccess)" during data authorization in gen2.

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-backend#1269]
### Environment information

```plain text
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 84.30 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_PROFILE = cloudteam
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I get the following type error
```
Property 'resource' has type '{ readonly public: (provider?: "apiKey" | "iam") => Authorization<"public", undefined, false> & { to: <SELF extends Authorization<any, any, any> >(this: SELF, operations: ("create" | "update" | ... 6 more ... | "search")[]) => Omit<...>; }; ... 7 more . ..; readonly custom: (provider?: "function") => Authorization<......' does not exist. ts(2339)
```

Data cannot be accessed from lambda.

```
errors: [
   UnauthorizedException: Unknown error
       at buildRestApiError (file:///var/task/index.mjs:30731:24)
       at parseRestApiServiceError (file:///var/task/index.mjs:30685:12)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async job (file:///var/task/index.mjs:30755:15)
       at async GraphQLAPIClass._graphql (file:///var/task/index.mjs:32170:38)
       at async _list (file:///var/task/index.mjs:32902:19)
       at async Runtime.handler (file:///var/task/index.mjs:34317:40) {
     recoverySuggestion: `If you're calling an Amplify-generated API, make sure to set the "authMode" in generateClient({ authMode: '...' }) to the backend authorization rule's auth provider ('apiKey', 'userPool' , 'iam', 'oidc', 'lambda')`
   }
]
```

lambda code is here
```
import type { PostConfirmationTriggerHandler } from "aws-lambda";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/data";
import { Schema } from "../../data/resource";
import config from "../amplifyconfiguration.json";

Amplify.configure(
  {
    API: {
      GraphQL: {
        endpoint: process.env.API_ENDPOINT,
        region: process.env.AWS_REGION,
        defaultAuthMode: "iam",
        modelIntrospection: config.modelIntrospection as never,
      },
    },
  },
  {
    Auth: {
      credentialsProvider: {
        getCredentialsAndIdentityId: async () => ({
          credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
            sessionToken: process.env.AWS_SESSION_TOKEN,
          },
        }),
        clearCredentialsAndIdentityId: () => {
          /* noop */
        },
      },
    },
  }
);

const dataClient = generateClient<Schema>({ authMode: "iam" });
```

**Comment by kekami** [comment]
Ensure you use 'env' as specified here [https://docs.amplify.aws/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/#access-the-api-using-aws-amplify](https://docs.amplify.aws/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/#access-the-api-using-aws-amplify)

**Comment by rnrnstar2** [comment]
Module '@env/function_name' or its corresponding type declaration not found.

Since I can't import it due to this error, I set GRAPHQL_ENDPOINT etc. directly to environment variables and use them.

Is env the cause of the auth error?

**Comment by kekami** [comment]
Not sure if that is what causing the with issue but could be. Have you authorized the function in the schema and passed the handler to 'defineBackend'?

**Comment by kekami** [comment]
Do you have any generated envs in '.amplify/generated/env/'?

**Comment by rnrnstar2** [comment]
Authentication for data cannot be granted to function using a.allow.resource(oripaPostConfirmation).

`.amplify/generated/env/` is not generated.
defineBackend is set as follows.

```
import { defineBackend } from "@aws-amplify/backend";
import { auth } from "./auth/resource";
import { data } from "./data/resource";
import { oripaPostConfirmation } from "./functions/oripaPostConfirmation/resource";

const backend = defineBackend({
  auth,
  data,
  oripaPostConfirmation,
});

// PasswordPolicy
const { cfnUserPool } = backend.auth.resources.cfnResources;
cfnUserPool.addPropertyOverride("Policies", {
  PasswordPolicy: {
    MinimumLength: 8,
    RequireLowercase: true,
    RequireNumbers: true,
    RequireSymbols: false,
    RequireUppercase: false,
    TemporaryPasswordValidityDays: 20,
  },
});
```


![スクリーンショット 2024-04-08 15 52 59](https://github.com/aws-amplify/amplify-backend/assets/39724729/ff5d0c15-3f15-4497-b0f0-bdbc291c5222)

**Comment by kekami** [comment]
What versions are you running of amplify? You environment info says:
```
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
```

Ensure you are running the beta version  `yarn add --save-dev @aws-amplify/backend@beta @aws-amplify/backend-cli@beta`

**Comment by rnrnstar2** [comment]
```
npx amplify info                                                                                  【 main 】
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 284.53 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.12.1
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_PROFILE = cloudteam
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

I updated the version, but ".amplify/generated/env/" is not there.

**Comment by kekami** [comment]
Ensure you are on:
```
    "@aws-amplify/backend": "0.13.0-beta.15",
    "@aws-amplify/backend-cli": "0.12.0-beta.17",
```

**Comment by rnrnstar2** [comment]
In the monorepo development environment, the project structure is `packages/shared-backend/amplify`.
Since we are using turborepo, there is no node_modules in the amplify directory.
Therefore, it will look like this:
````
@aws-amplify/backend: Not Found
@aws-amplify/backend-cli: Not Found
````

What should I do in this case?

**Comment by kekami** [comment]
If you run `npx amplify info` in your workspace root it will probably pick up the versions. Otherwise ensure that the correct versions are specified in your package.json.

**Comment by rnrnstar2** [comment]
```
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 50.06 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.15
  @aws-amplify/backend-cli: 0.12.0-beta.17
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

Yes, you will get the version when you run it as root.
However, running `npx amplify sandbox --debug` is not root.
What should I do in this case?

**Comment by kekami** [comment]
I don't know the specifics of turbo repo. However you are still missing:
```
 aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
```

Perhaps that causes the type error with `a.allow.resource()`

**Comment by rnrnstar2** [comment]
```
npx amplify info                                                                                                           【 main 】
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 524.39 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.15
  @aws-amplify/backend-cli: 0.12.0-beta.17
  aws-amplify: 6.0.27
  aws-cdk: 2.136.0
  aws-cdk-lib: 2.136.0
  typescript: 5.4.4
AWS environment variables:
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

In this situation, if you set `a.allow.resource(oripaPostConfirmation)` to authenticate data, the following error will occur.

```
amplify/data/resource.ts(34,7): error TS2322: Type 'ResourceAuthorization & { to: <SELF extends ResourceAuthorization>(this: SELF, operations: ("listen" | "query" | "mutate")[]) => Omit<SELF, "to">; }' is not assignable to type 'Authorization<any, any, any>'.
  Types of property '[__data]' are incompatible.
    Property 'multiOwner' is missing in type 'ResourceAuthorizationData' but required in type '{ strategy?: any; provider?: "function" | "userPools" | "iam" | "apiKey" | "oidc"; operations?: ("create" | "update" | "delete" | "read" | "get" | "list" | "sync" | "listen" | "search")[]; ... 4 more ...; groupClaim?: string; }'.

amplify/data/resource.ts(34,7): error TS2322: Type 'ResourceAuthorization & { to: <SELF extends ResourceAuthorization>(this: SELF, operations: ("listen" | "query" | "mutate")[]) => Omit<SELF, "to">; }' is not assignable to type 'Authorization<any, any, any>'.
  Types of property '[__data]' are incompatible.
    Property 'multiOwner' is missing in type 'ResourceAuthorizationData' but required in type '{ strategy?: any; provider?: "function" | "userPools" | "iam" | "apiKey" | "oidc"; operations?: ("create" | "update" | "delete" | "read" | "get" | "list" | "sync" | "listen" | "search")[]; ... 4 more ...; groupClaim?: string; }'.
TypeScript validation check failed.
Resolution: Fix the syntax and type errors in your backend definition.
```

import { env } from '@env/oripaPostConfirmation';
cannot be imported because it does not exist.

**Comment by edwardfoyle** [comment]
Hi @rnrnstar2, I think there are a couple things going on here.
1. The env import should be `import { env } from '$amplify/env/oripaPostConfirmation'`. If you set up your project using an older version of gen 2, you may also need to manually update the paths in your `tsconfig.json`. You can find more info on that here: https://docs.amplify.aws/gen2/build-a-backend/functions/#accessing-environment-variables (expand the "learn more" section). Also make sure that you run `npx amplify sandbox` to generate the env file.
2. I think all of the above is a red herring regarding the type error that your are getting in your backend definition. Can you try deleting your package lock and node_modules and doing a fresh install? I think you may have an outdated backend package somewhere that is not resolving the new resource access rule.

**Comment by rnrnstar2** [comment]
I solved it by reinstalling and changing tsconfig.json.
thank you!
