### ISSUE TITLE
Unable to model multiple relationships between two models after 1.0 release (worked before)

### ISSUE THREAD

**Issue by m9rc1n** [aws-amplify/amplify-backend#1461]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 174.31 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: 1.22.18 - /opt/homebrew/bin/yarn
  npm: 10.3.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.3.0
  aws-cdk: 2.140.0
  aws-cdk-lib: 2.140.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Hi guys!

Small error discovered after recent update:

To reproduce:

- Upgrade to latest amplify tools
- Follow up https://docs.amplify.aws/react/build-a-backend/data/data-modeling/relationships/#model-multiple-relationships-between-two-models

Console output

```
(base) ➜  example git:(main) ✗ npx ampx sandbox --debug
[INFO] 2024-05-08T05:08:53.397Z:   
  Amplify Sandbox
  
[INFO] 2024-05-08T05:08:53.397Z:   Identifier:  marcin
[INFO] 2024-05-08T05:08:53.397Z:   Stack:       amplify-example-marcin-sandbox-d89abf9326
[INFO] 2024-05-08T05:08:53.397Z:   
  To specify a different sandbox identifier, use --identifier
[DEBUG] 2024-05-08T05:08:53.402Z: [Sandbox] Executing command `deploy`
[DEBUG] 2024-05-08T05:08:55.967Z: /Users/marcin/Projects/example/node_modules/@aws-amplify/backend-data/src/factory.ts:252
      throw new AmplifyUserError(
            ^


AmplifyError [AmplifyDataConstructInitializationError]: Failed to instantiate data construct
    at DataGenerator.generateContainerEntry (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend-data/src/factory.ts:252:13)
    at SingletonConstructContainer.getOrCompute (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend/src/engine/singleton_construct_container.ts:51:19)
    at DataFactory.getInstance (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend-data/src/factory.ts:109:31)
    at <anonymous> (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend/src/backend_factory.ts:115:68)
    at Array.forEach (<anonymous>)
    at BackendFactory (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend/src/backend_factory.ts:111:40)
    at defineBackend (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend/src/backend_factory.ts:155:19)
    at <anonymous> (/Users/marcin/Projects/example/amplify/backend.ts:8:17)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  cause: Error
      at validateReferencesBidirectionality (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-relational-transformer/src/utils.ts:376:11)
      at HasManyDirectiveDDBReferencesTransformer.HasManyDirectiveDDBReferencesTransformer.validate (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-relational-transformer/src/has-many/has-many-directive-ddb-references-transformer.ts:75:39)
      at validate (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-relational-transformer/src/graphql-has-many-transformer.ts:183:30)
      at HasManyTransformer.HasManyTransformer.field (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-relational-transformer/src/graphql-has-many-transformer.ts:75:5)
      at GraphQLTransform.transformField (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:482:25)
      at GraphQLTransform.transformObject (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:460:12)
      at GraphQLTransform.transform (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer-core/src/transformation/transform.ts:254:18)
      at executeTransform (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-transformer/src/graphql-transformer.ts:166:15)
      at AmplifyGraphqlApi (/Users/marcin/Projects/example/node_modules/@aws-amplify/graphql-api-construct/src/amplify-graphql-api.ts:222:21)
      at DataGenerator.generateContainerEntry (/Users/marcin/Projects/example/node_modules/@aws-amplify/backend-data/src/factory.ts:236:20),
  classification: 'ERROR',
  options: {
    message: 'Failed to instantiate data construct',
    resolution: 'See the underlying error message for more details.'
  },
  serializedError: '{"name":"AmplifyDataConstructInitializationError","classification":"ERROR","options":{"message":"Failed to instantiate data construct","resolution":"See the underlying error message for more details."},"cause":{"name":"Error","message":""}}',
  resolution: 'See the underlying error message for more details.',
  details: undefined,
  link: undefined,
  code: undefined
}

Node.js v20.11.0

[DEBUG] 2024-05-08T05:08:56.001Z: 


[DEBUG] 2024-05-08T05:08:56.002Z: Subprocess exited with error 1

[DEBUG] 2024-05-08T05:08:56.322Z: {
    "compilerOptions": {
        "target": "es2022",
        "module": "es2022",
        "moduleResolution": "bundler",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "paths": {
            "$amplify/*": [
                "../.amplify/generated/*"
            ]
        },
        "allowSyntheticDefaultImports": true,
        "resolvePackageJsonExports": true,
        "resolvePackageJsonImports": true,
        "useDefineForClassFields": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "alwaysStrict": true,
        "useUnknownInCatchVariables": true
    },
    "files": [
        "./backend.ts",
        "./auth/resource.ts",
        "./data/resource.ts"
    ]
}

Failed to instantiate data construct
Resolution: See the underlying error message for more details.
```

Note: I could not find underlying error message

**Comment by m9rc1n** [comment]
Similar error when modelling parent-children relationships:

```
    Competition: a
      .model({
        name: a.string(),
        parentId: a.id(),
        parent: a.belongsTo(
          'Competition',
          'parentId'
        ),
        children: a.hasMany(
          'Competition',
          'parentId'
        ),
      })
      .authorization((allow) => [
        allow.owner(),
        allow.publicApiKey().to(['read']),
      ]),
```

**Comment by ykethan** [comment]
Hey @m9rc1n, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-category-api/issues/2531. The Amplify team is currently working on a fix: https://github.com/aws-amplify/amplify-category-api/issues/2531#issuecomment-2099123864. Do add any additional information to the issue linked that would assist with the investigation. 
Closing this issue to prevent any miscommunication between issues.
