### ISSUE TITLE
Gen 2 - Deployment Failure in Yarn Workspaces Monorepo: BackendSynthError: Unable to build the Amplify backend definition.

### ISSUE THREAD

**Issue by jgo80** [aws-amplify/amplify-backend#1512]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 3.10 GB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.1.0 - /opt/homebrew/bin/node
  Yarn: 4.2.2 - /opt/homebrew/bin/yarn
  npm: 10.7.0 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-cli: Not Found
  aws-amplify: Not Found
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: Not Found
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

Attempting to deploy a Monorepo using Yarn Workspaces (version 4.2.2) following the official documentation for Monorepos results in a build phase error during deployment.

```
BackendSynthError: Unable to build the Amplify backend definition.
Resolution: Check your backend definition in the `amplify` folder for syntax and type errors.
Cause: Error: Failed to bundle asset amplify-d1tvmalw5gea2l-main-branch-b567149f85/AmplifyBranchLinker/CustomResourceLambda/Code/Stage
```

The error occurs when `yarn ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID` is executed.
My App ID is: d3g7fegy2pqutf

## Repository Structure
**amr** stands for Amplify Mono Repo
**amrb** stands for Amplify Mono Repo Backend
```
./
├── packages/
│   └── amrb/
│       ├── amplify/
│       │   ├── auth/
│       │   │   └── resource.ts
│       │   ├── backend.ts
│       │   └── tsconfig.json
│       └── package.json
├── package.json
└── yarn.lock
```

## Additional Information

- The backend definition is verified to be correct and functional in a single-repo environment.
- No changes were made to the backend code before attempting the monorepo deployment.

## Expected Behavior
- Deploy backend from a Yarn Workspace w/o error

## Steps to Reproduce

1. Clone the repository from [GitHub](https://github.com/jgo80/amr).
2. Follow the deployment steps as outlined in the official documentation linked [here](https://docs.amplify.aws/react-native/deploy-and-host/fullstack-branching/monorepos/).

This is the **`amplify.yml`** that is generated automatically
```
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - corepack enable
            - yarn set version stable
            - yarn config set nodeLinker node-modules
            - yarn install --immutable
            - yarn ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
    frontend:
      phases:
        build:
          commands:
            - mkdir ./dist && touch ./dist/index.html
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      buildPath: packages/amrb
    appRoot: packages/amrb
```

## Complete Build Log
<details>
 <summary>Show complete log</summary>

```
2024-05-14T06:05:54.808Z [INFO]: # Cloning repository: git@github.com:jgo80/am.git
2024-05-14T06:05:56.023Z [INFO]: 
2024-05-14T06:05:56.023Z [INFO]: Cloning into 'am'...
2024-05-14T06:05:56.023Z [INFO]: # Switching to commit: 94f3bf0c8a7d1738df1674bc498ba18f377d71e0
2024-05-14T06:05:56.036Z [INFO]: Note: switching to '94f3bf0c8a7d1738df1674bc498ba18f377d71e0'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at 94f3bf0 add amplify backend
2024-05-14T06:05:56.115Z [INFO]: Successfully cleaned up Git credentials
2024-05-14T06:05:56.115Z [INFO]: # Checking for Git submodules at: /codebuild/output/src862822659/src/am/.gitmodules
2024-05-14T06:05:56.122Z [INFO]: # Retrieving environment cache...
2024-05-14T06:05:56.167Z [WARNING]: ! Unable to write cache: {"code":"ERR_BAD_REQUEST","message":"Request failed with status code 404"})}
2024-05-14T06:05:56.167Z [INFO]: ---- Setting Up SSM Secrets ----
2024-05-14T06:05:56.167Z [INFO]: SSM params {"Path":"/amplify/d2qepv3se0zdeg/develop/","WithDecryption":true}
2024-05-14T06:05:57.028Z [INFO]: No live updates for this build run
2024-05-14T06:05:57.032Z [INFO]: # Retrieving cache...
2024-05-14T06:05:57.077Z [INFO]: # Retrieved cache
2024-05-14T06:06:14.078Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: corepack enable
2024-05-14T06:06:14.558Z [INFO]: # Executing command: yarn set version stable
2024-05-14T06:06:15.662Z [INFO]: ➤ YN0000: Done in 0s 5ms
2024-05-14T06:06:15.680Z [INFO]: # Executing command: yarn config set nodeLinker node-modules
2024-05-14T06:06:15.922Z [INFO]: ➤ YN0000: Successfully set nodeLinker to 'node-modules'
2024-05-14T06:06:15.939Z [INFO]: # Executing command: yarn install --immutable
2024-05-14T06:06:16.317Z [INFO]: ➤ YN0000: · Yarn 4.2.2
2024-05-14T06:06:16.337Z [INFO]: ➤ YN0000: ┌ Resolution step
2024-05-14T06:06:16.718Z [INFO]: ➤ YN0000: └ Completed in 0s 381ms
2024-05-14T06:06:16.720Z [INFO]: ➤ YN0000: ┌ Post-resolution validation
2024-05-14T06:06:16.720Z [INFO]: ➤ YN0002: │ amb@workspace:backends/amb doesn't provide @aws-sdk/types (pc9d2e), requested by @aws-amplify/backend-cli.
2024-05-14T06:06:16.720Z [INFO]: ➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
2024-05-14T06:06:16.779Z [INFO]: ➤ YN0000: └ Completed
2024-05-14T06:06:16.779Z [INFO]: ➤ YN0000: ┌ Fetch step
2024-05-14T06:06:39.604Z [INFO]: ➤ YN0013: │ 930 packages were added to the project (+ 901.76 MiB).
2024-05-14T06:06:39.612Z [INFO]: ➤ YN0000: └ Completed in 22s 825ms
2024-05-14T06:06:39.658Z [INFO]: ➤ YN0000: ┌ Link step
2024-05-14T06:06:49.558Z [INFO]: ➤ YN0007: │ esbuild@npm:0.21.2 must be built because it never has been before or the last one failed
2024-05-14T06:06:49.566Z [INFO]: ➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
                                 ➤ YN0007: │ core-js@npm:3.37.0 must be built because it never has been before or the last one failed
                                 ➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
2024-05-14T06:06:49.839Z [INFO]: ➤ YN0000: │ core-js@npm:3.37.0 STDOUT Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2024-05-14T06:06:49.839Z [INFO]: ➤ YN0000: │ core-js@npm:3.37.0 STDOUT
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT The project needs your help! Please consider supporting core-js:
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT > https://opencollective.com/core-js
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT > https://patreon.com/zloirock
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT > https://boosty.to/zloirock
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
                                 ➤ YN0000: │ core-js@npm:3.37.0 STDOUT
2024-05-14T06:06:49.860Z [INFO]: ➤ YN0000: │ core-js@npm:2.6.12 STDOUT Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2024-05-14T06:06:49.860Z [INFO]: ➤ YN0000: │ core-js@npm:2.6.12 STDOUT
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT > https://opencollective.com/core-js
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT > https://www.patreon.com/zloirock
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
                                 ➤ YN0000: │ core-js@npm:2.6.12 STDOUT
2024-05-14T06:06:50.167Z [INFO]: ➤ YN0000: └ Completed in 10s 509ms
2024-05-14T06:06:50.279Z [INFO]: ➤ YN0000: · Done with warnings in 33s 963ms
2024-05-14T06:06:50.492Z [INFO]: # Executing command: yarn ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
2024-05-14T06:06:58.464Z [INFO]: 
2024-05-14T06:07:04.357Z [INFO]: 
2024-05-14T06:07:04.363Z [INFO]: BackendSynthError: Unable to build the Amplify backend definition.
                                 Resolution: Check your backend definition in the `amplify` folder for syntax and type errors.
                                 Cause: Error: Failed to bundle asset amplify-d2qepv3se0zdeg-develop-branch-4c7556fe77/AmplifyBranchLinker/CustomResourceLambda/Code/Stage, bundle output is located at /codebuild/output/src862822659/src/am/backends/amb/.amplify/artifacts/cdk.out/bundling-temp-f9e59975137dde191e19bb714b5af56177b279c5e19315162c012e1eee695ada-error: Error: bash -c yarn run esbuild --bundle "/codebuild/output/src862822659/src/am/node_modules/@aws-amplify/backend/lib/engine/branch-linker/lambda/branch_linker.js" --target=node18 --platform=node --outfile="/codebuild/output/src862822659/src/am/backends/amb/.amplify/artifacts/cdk.out/bundling-temp-f9e59975137dde191e19bb714b5af56177b279c5e19315162c012e1eee695ada/index.js" run in directory /codebuild/output/src862822659/src/am exited with status 1
                                 at AssetStaging.bundle (/codebuild/output/src862822659/src/am/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:619)
                                 BackendSynthError: Unable to build the Amplify backend definition.
                                 Resolution: Check your backend definition in the `amplify` folder for syntax and type errors.
                                 Cause: Error: Failed to bundle asset amplify-d2qepv3se0zdeg-develop-branch-4c7556fe77/AmplifyBranchLinker/CustomResourceLambda/Code/Stage, bundle output is located at /codebuild/output/src862822659/src/am/backends/amb/.amplify/artifacts/cdk.out/bundling-temp-f9e59975137dde191e19bb714b5af56177b279c5e19315162c012e1eee695ada-error: Error: bash -c yarn run esbuild --bundle "/codebuild/output/src862822659/src/am/node_modules/@aws-amplify/backend/lib/engine/branch-linker/lambda/branch_linker.js" --target=node18 --platform=node --outfile="/codebuild/output/src862822659/src/am/backends/amb/.amplify/artifacts/cdk.out/bundling-temp-f9e59975137dde191e19bb714b5af56177b279c5e19315162c012e1eee695ada/index.js" run in directory /codebuild/output/src862822659/src/am exited with status 1
                                 at AssetStaging.bundle (/codebuild/output/src862822659/src/am/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:619)
2024-05-14T06:07:04.363Z [WARNING]: ampx pipeline-deploy
                                    Command to deploy backends in a custom CI/CD pipeline. This command is not inten
                                    ded to be used locally.
                                    Options:
                                    --debug            Print debug logs to the console  [boolean] [default: false]
                                    --help             Show help                                         [boolean]
                                    --branch           Name of the git branch being deployed   [string] [required]
                                    --app-id           The app id of the target Amplify app    [string] [required]
                                    --outputs-out-dir  A path to directory where amplify_outputs is written. If no
                                    t provided defaults to current process working directory.
                                    [string]
                                    --outputs-version  Version of the configuration. Version 0 represents classic
                                    amplify-cli config file amplify-configuration and 1 represe
                                    nts newer config file amplify_outputs
                                    [string] [choices: "0", "1"] [default: "1"]
2024-05-14T06:07:04.478Z [ERROR]: !!! Build failed
2024-05-14T06:07:04.478Z [ERROR]: !!! Error: Command failed with exit code 1
2024-05-14T06:07:04.478Z [INFO]: # Starting environment caching...
2024-05-14T06:07:04.478Z [INFO]: # Environment caching completed
```
</details>

**Comment by jgo80** [comment]
Eeehm... is the simple error probably that the script calls `bash -c yarn run esbuild ...`? I guess the original is `bash -c npm run esbuild`. For yarn it should read `bash -c yarn esbuild` w/o the run syntax.

**Comment by edwardfoyle** [comment]
Hi @jgo80, it looks like CDK was unable to execute `esbuild` when bundling the lambda functions in the project. Can you make sure that `yarn run esbuild` is able to find the `esbuild` executable in your project? If not, you can try deleting your node_modules and yarn.lock file and reinstalling.

**Comment by jgo80** [comment]
Hi @edwardfoyle , thanks for digging into this. I deleted node_modules and yarn.lock so many times, this is not the cause. `yarn run esbuild` itself is working fine in locally.

I mocked the path to the node module `yarn run esbuild --bundle "../../node_modules/@aws-amplify/backend/lib/engine/branch-linker/lambda/branch_linker.js"` and I got this result

```
 yarn run esbuild --bundle "../../node_modules/@aws-amplify/backend/lib/engine/branch-linker/lambda/branch_linker.js"
✘ [ERROR] Could not resolve "node:crypto"

    ../../node_modules/@aws-amplify/backend/lib/engine/branch-linker/lambda/branch_linker.js:1:27:
      1 │ import { randomUUID } from 'node:crypto';
        ╵                            ~~~~~~~~~~~~~

  The package "node:crypto" wasn't found on the file system but is built into node. Are you trying
  to bundle for node? You can use "--platform=node" to do that, which will remove this error.

1 error
node:child_process:928
    throw err;
    ^
```

The Error happens in the amplify backend during CI/CD build phase! So the error must be on the amplify side...
Please follow my reproduction steps with my sample git provided. Thanks so much!

**Comment by jgo80** [comment]
@edwardfoyle can you confirm this? Currently no monorepo is deployable to amplify (neither with yarn nor with npm). It's actually quite a big show stopper for me. Thanks for your help 🙏

**Comment by josefaidt** [comment]
Hey @jgo80 can you try installing `esbuild` in your monorepo root to see if this resolves the build issue? We've seen this with pnpm where esbuild's bin is linked in the monorepo package but CDK is executing from the root, which is where it cannot find the esbuild bin because it is not explicitly declared as a dep at the project root.

This seems similar to https://github.com/aws/aws-cdk/issues/24021, but for yarn

**Comment by jgo80** [comment]
@josefaidt thank you, it worked! 🙏 You made my day! 😃🙏 Even if it is only a workaround in this state. it should at least be documented! Thanks again!
