### ISSUE TITLE
SQLSchema - Optional belongsTo relationship breaks query/mutations

### ISSUE THREAD

**Issue by kekami** [aws-amplify/amplify-backend#1574]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 157.84 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: 3.8.2 - ~/.nvm/versions/node/v20.12.2/bin/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.2
  aws-cdk: 2.142.1
  aws-cdk-lib: 2.142.1
  typescript: 5.4.5
AWS environment variables:
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Description

Schema:
```
    models.Contract.relationships({
      organisation: a.belongsTo('Organisation', 'organisation_id'),
    }),
    
    models.Organisation.relationships({
      contracts: a.hasMany('Contract', 'organisation_id'),
    }),

```

On running `createContract` mutation, the following error is received.

```
2024-05-28T20:08:54.908Z	a6df0c55-d6bc-4407-b261-eff561811370	INFO	error: select * from "organisations" where "id" = $1 - invalid input syntax for type uuid: ""
    at Parser.parseErrorMessage (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/opt/nodejs/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 129,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: "unnamed portal parameter $1 = ''",
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'uuid.c',
  line: '133',
  routine: 'string_to_uuid'
}
```

Presumably due to the following line in the `ContractOrganisationDataResolverFn` where it defaults to `""` if the created `Contract` has no `organisation_id` (optional relationship)
```
$util.qr($lambdaInput.args.input.put("id", $util.defaultIfNull($ctx.source.organisation_id, "")))
{
  "version": "2018-05-29",
  "operation": "Invoke",
  "payload":   $util.toJson($lambdaInput)
}
```

Same error is also received when querying `Contract` with no `organisation_id`, e.g.
```
query MyQuery {
  listContracts {
    items {
      id
     	organisation {
          id
        }
    }
  }
}

```

Ping me if you have any further questions.

**Comment by ykethan** [comment]
Hey👋 thanks for raising this! I'm going to transfer this over to our API repository for better assistance 🙂
