### ISSUE TITLE
`npx ampx sandbox` fails with `ParameterNotFound: UnknownError`

### ISSUE THREAD

**Issue by ikonyshev** [aws-amplify/amplify-backend#1616]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 185.52 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
  Yarn: 1.22.22 - /opt/homebrew/bin/yarn
  npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.4
  aws-cdk: 2.144.0
  aws-cdk-lib: 2.144.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I'm trying to setup a Swift project following this tutorial https://docs.amplify.aws/swift/start/quickstart/
I created a new AWS account and amplify-admin user following this tutorial https://docs.amplify.aws/swift/start/account-setup/

When I'm running `npx ampx sandbox --debug` I get the following output:

```
ampx sandbox

Starts sandbox, watch mode for Amplify backend deployments

Commands:
  ampx sandbox delete            Deletes sandbox environment
  ampx sandbox secret <command>  Manage sandbox secrets

Options:
  --debug            Print debug logs to the console  [boolean] [default: false]
  --help             Show help                                         [boolean]
  --dir-to-watch     Directory to watch for file changes. All subdirectories and
                      files will be included. Defaults to the amplify directory.
                                                                        [string]
  --exclude          An array of paths or glob patterns to ignore. Paths can be
                     relative or absolute and can either be files or directories
                                                                         [array]
  --identifier       An optional identifier to distinguish between different san
                     dboxes. Default is the name of the system user executing th
                     e process                                          [string]
  --outputs-format   amplify_outputs file format
                  [string] [choices: "mjs", "json", "json-mobile", "ts", "dart"]
  --outputs-version  Version of the configuration. Version 0 represents classic
                     amplify-cli config file amplify-configuration and 1 represe
                     nts newer config file amplify_outputs
                                     [string] [choices: "0", "1"] [default: "1"]
  --outputs-out-dir  A path to directory where amplify_outputs is written. If no
                     t provided defaults to current process working directory.
                                                                        [string]
  --profile          An AWS profile name.                               [string]
  --once             Execute a single sandbox deployment without watching for fu
                     ture file changes                                 [boolean]

ParameterNotFound: UnknownError
[DEBUG] 2024-06-05T14:18:09.579Z: ParameterNotFound: UnknownError
    at de_ParameterNotFoundRes (/Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/client-ssm/dist-cjs/index.js:7923:21)
    at de_CommandError (/Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/client-ssm/dist-cjs/index.js:6758:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async FileWatchingSandbox.isBootstrapped (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/sandbox/lib/file_watching_sandbox.js:233:46)
    at async FileWatchingSandbox.start (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/sandbox/lib/file_watching_sandbox.js:85:30)
    at async Object.handler (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/backend-cli/lib/commands/sandbox/sandbox_command.js:61:9)
ParameterNotFound: UnknownError
[DEBUG] 2024-06-05T14:18:09.582Z: ParameterNotFound: UnknownError
    at de_ParameterNotFoundRes (/Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/client-ssm/dist-cjs/index.js:7923:21)
    at de_CommandError (/Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/client-ssm/dist-cjs/index.js:6758:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/ivan/Development/alarm/Alarm/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async FileWatchingSandbox.isBootstrapped (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/sandbox/lib/file_watching_sandbox.js:233:46)
    at async FileWatchingSandbox.start (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/sandbox/lib/file_watching_sandbox.js:85:30)
    at async Object.handler (file:///Users/ivan/Development/alarm/Alarm/node_modules/@aws-amplify/backend-cli/lib/commands/sandbox/sandbox_command.js:61:9)
```

**Comment by ikonyshev** [comment]
It seems create environment step is missing in docs and it isn't clear how to do that for native app project

**Comment by ikonyshev** [comment]
Thanks, it works now. However, this step is not mentioned in the documentation. The current version of the documentation [says](https://docs.amplify.aws/swift/start/account-setup/#5-bootstrap-your-aws-account) `npx ampx sandbox` has to start bootstrapping during the first run.

**Comment by sobolk** [comment]
Fixed in https://github.com/aws-amplify/amplify-backend/releases/tag/%40aws-amplify%2Fsandbox%401.0.4 .
