### ISSUE TITLE
SecretFetcherResource TIMEOUT during deployments (SIWA)

### ISSUE THREAD

**Issue by TimRoadley** [aws-amplify/amplify-backend#1943]
### Environment information

```plain text
System:
  OS: macOS 13.6.7
  CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Memory: 1.21 GB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.1.0 - /usr/local/bin/node
  Yarn: 1.22.22 - /usr/local/bin/yarn
  npm: 10.8.3 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: 1.3.0
  @aws-amplify/backend: 1.2.0
  @aws-amplify/backend-auth: 1.1.3
  @aws-amplify/backend-cli: 1.2.5
  @aws-amplify/backend-data: 1.1.3
  @aws-amplify/backend-deployer: 1.1.0
  @aws-amplify/backend-function: 1.3.4
  @aws-amplify/backend-output-schemas: 1.2.0
  @aws-amplify/backend-output-storage: 1.1.1
  @aws-amplify/backend-secret: 1.1.0
  @aws-amplify/backend-storage: 1.1.2
  @aws-amplify/cli-core: 1.1.2
  @aws-amplify/client-config: 1.3.0
  @aws-amplify/deployed-backend-client: 1.4.0
  @aws-amplify/form-generator: 1.0.1
  @aws-amplify/model-generator: 1.0.5
  @aws-amplify/platform-core: 1.0.7
  @aws-amplify/plugin-types: 1.2.1
  @aws-amplify/sandbox: 1.2.0
  @aws-amplify/schema-generator: 1.2.1
  aws-amplify: 6.5.3
  aws-cdk: 2.155.0
  aws-cdk-lib: 2.155.0
  typescript: 5.5.4
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

When deploying my app, it **fails 50%-75% of the time** if I have **signInWithApple** enabled. I can just keep hitting "redeploy this version" and eventually it'll work.

When deploying my app, it **works 100% of the time** if I remove this code from `amplify/auth/resource.ts`:

```
      signInWithApple: {
        clientId: secret("SIWA_CLIENT_ID"),
        keyId: secret("SIWA_KEY_ID"),
        privateKey: secret("SIWA_PRIVATE_KEY"),
        teamId: secret("SIWA_TEAM_ID"),
        scopes: ["email", "name"],
        attributeMapping: {
          email: "email",
          givenName: "firstName",
          familyName: "lastName",
        },
      },
```

Here are the logs where SecretFetcherResource has a timeout issue.

```
amplify-d1vq90xadjad2j-prod-branch-241a11f210-auth179371D7-LXVYLRURGBX6 | 3/5 | 11:36:54 AM | [0mCREATE_IN_PROGRESS [0m | Custom::SecretFetcherResource | [0m[1mauth/SIWA_PRIVATE_KEYSecretFetcherResource/Default[22m[0m (SIWAPRIVATEKEYSecretFetcherResource) [36m[1mResource creation Initiated[22m[39m

98

amplify-d1vq90xadjad2j-prod-branch-241a11f210-auth179371D7-LXVYLRURGBX6 | 4/5 | 11:36:54 AM | [32mUPDATE_COMPLETE [39m | Custom::SecretFetcherResource | [32m[1mauth/GOOGLE_CLIENT_SECRETSecretFetcherResource/Default[22m[39m (GOOGLECLIENTSECRETSecretFetcherResource)

99

amplify-d1vq90xadjad2j-prod-branch-241a11f210-auth179371D7-LXVYLRURGBX6 | 5/5 | 11:36:54 AM | [32mCREATE_COMPLETE [39m | Custom::SecretFetcherResource | [32m[1mauth/SIWA_KEY_IDSecretFetcherResource/Default[22m[39m (SIWAKEYIDSecretFetcherResource)

100

amplify-d1vq90xadjad2j-prod-branch-241a11f210-auth179371D7-LXVYLRURGBX6 | 6/5 | 11:36:54 AM | [32mCREATE_COMPLETE [39m | Custom::SecretFetcherResource | [32m[1mauth/SIWA_PRIVATE_KEYSecretFetcherResource/Default[22m[39m (SIWAPRIVATEKEYSecretFetcherResource)

101

amplify-d1vq90xadjad2j-prod-branch-241a11f210-auth179371D7-LXVYLRURGBX6 | 6/5 | 11:40:10 AM | [31mUPDATE_FAILED [39m | Custom::SecretFetcherResource | [31m[1mauth/GOOGLE_CLIENT_IDSecretFetcherResource/Default[22m[39m (GOOGLECLIENTIDSecretFetcherResource) [31m[1mReceived response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}[22m[39m

102

[31m[1m at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)[22m[39m

103

[31m[1m at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5826:49)[22m[39m

104

[31m[1m at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[22m[39m

105

[31m[1m at async defaultInvokeFunction (/var/task/outbound.js:1:1024)[22m[39m

106

[31m[1m at async invokeUserFunction (/var/task/framework.js:1:2740)[22m[39m

107

[31m[1m at async onEvent (/var/task/framework.js:1:369)[22m[39m

108

[31m[1m at async Runtime.handler (/var/task/cfn-response.js:1:1826) (RequestId: ed892f44-f6f3-47aa-b327-7b0adc288ad7)
```

### Reproduction steps

To reproduce this issue, set your external providers as follows, then run a build.

```
    externalProviders: {
      google: {
        clientId: secret("GOOGLE_CLIENT_ID"),
        clientSecret: secret("GOOGLE_CLIENT_SECRET"),
        scopes: ["openid", "email", "profile"],
        attributeMapping: {
          email: "email",
          givenName: "given_name",
          familyName: "family_name",
        },
      },
      signInWithApple: {
        clientId: secret("SIWA_CLIENT_ID"),
        keyId: secret("SIWA_KEY_ID"),
        privateKey: secret("SIWA_PRIVATE_KEY"),
        teamId: secret("SIWA_TEAM_ID"),
        scopes: ["email", "name"],
        attributeMapping: {
          email: "email",
          givenName: "firstName",
          familyName: "lastName",
        },
      },
```

**Comment by TimRoadley** [comment]
Oh wow thank you @ykethan - I do have a limit of 10.  

I have requested this be raised to the "default" of 1000 and expect that should resolve the issue!
