### ISSUE TITLE
Issue with Sharing Schema Type Definitions

### ISSUE THREAD

**Issue by braian125** [aws-amplify/amplify-backend#2048]
### Environment information

```plain text
System:
  OS: macOS 13.6
  CPU: (8) arm64 Apple M1
  Memory: 96.55 MB / 8.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.3.0 - /opt/homebrew/bin/node
  Yarn: undefined - undefined
  npm: 10.8.1 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/auth-construct: Not Found
  @aws-amplify/backend: Not Found
  @aws-amplify/backend-auth: Not Found
  @aws-amplify/backend-cli: 1.2.6
  @aws-amplify/backend-data: Not Found
  @aws-amplify/backend-deployer: 1.1.1
  @aws-amplify/backend-function: Not Found
  @aws-amplify/backend-output-schemas: 1.2.0
  @aws-amplify/backend-output-storage: Not Found
  @aws-amplify/backend-secret: 1.1.1
  @aws-amplify/backend-storage: Not Found
  @aws-amplify/cli-core: 1.1.2
  @aws-amplify/client-config: 1.3.0
  @aws-amplify/deployed-backend-client: 1.4.0
  @aws-amplify/form-generator: 1.0.1
  @aws-amplify/model-generator: 1.0.5
  @aws-amplify/platform-core: 1.1.0
  @aws-amplify/plugin-types: 1.2.1
  @aws-amplify/sandbox: 1.2.1
  @aws-amplify/schema-generator: 1.2.1
  aws-amplify: 6.6.0
  aws-cdk: 2.157.0
  aws-cdk-lib: 2.157.0
  typescript: 5.6.2
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

Hello everyone,
I am currently working on a project that requires using the same backend. I have hosted it in two different repositories and followed the Sharing schema type definitions guide to share the schema types.

I’m not getting any type errors; however, I am encountering the following error:

```
TypeError: Cannot read properties of undefined (reading 'list')
    at DepartureRepositoryImpl.listDepartures (infraestructure/adapters/DepartureRepositoryImpl.ts:23:81)
    at DepartureService.listDepartures (application/services/DepartureService.ts:10:47)
    at PageDepartures (./src/app/departures/page.tsx:25:47)
    at stringify (<anonymous>)
```

source code I am implementing below

```
import { DepartureRepository } from '@/(architecture)/domain/repositories/DepartureRepository'
import { generateClient } from 'aws-amplify/data'
import { type Schema } from '@/data-schema'
import { Amplify } from 'aws-amplify'
import outputs from './../../../../amplify_outputs.json'
import type { SelectionSet } from 'aws-amplify/data'

Amplify.configure(outputs)

export type DepartureFilter = {
  ...
}


const selectionSet = ['id', 'startDay', 'endDay', 'price', 'season.name', 'createdAt', 'updatedAt'] as const
export type DepartureWithSeason = SelectionSet<Schema['Departure']['type'], typeof selectionSet>

export class DepartureRepositoryImpl implements DepartureRepository {
  private client = generateClient<Schema>({ authMode: "apiKey" })

  async listDepartures(
    filter?: DepartureFilter,
    limit?: number,
    nextToken?: string
  ): Promise<Array<DepartureWithSeason>> {
    const { data: departures, errors } = await this.client.models.Departure.list({
      selectionSet,
      filter,
      limit,
      nextToken,
    })
    if (errors) {
      console.error("Error listing todos", errors)
      throw new Error('Error fetching todos')
    }
    return departures
  }
}
```

```
"paths": {
      ...
      "@/data-schema": ["./../../comviajes/amplify/data/resource"]
    },
```

someone had a problem like this?
am I too tired and I’m missing something?

thank you for your help

### Reproduction steps

<img width="998" alt="image" src="https://github.com/user-attachments/assets/df6487f8-9e87-4275-b46e-bb7bd75d7ebd">

**Comment by ykethan** [comment]
Hey, thanks for raising this! I'm going to transfer this over to our API repository for better assistance 🙂
