### ISSUE TITLE
`npx ampx info` fails to run

### ISSUE THREAD

**Issue by Ao1K** [aws-amplify/amplify-backend#2369]
### Environment information

```plain text
PS C:\Users\Chet\Documents\theProject\amplify-next-template> npx ampx info --debug

ampx info

Generates information for Amplify troubleshooting

Options:
      --debug  Print debug logs to the console        [boolean] [default: false]
  -h, --help   Show help                                               [boolean]

Error: Command failed: wmic os get Caption
os - Alias not found.


[DEBUG] 2024-12-24T21:15:07.785Z: Error: Command failed: wmic os get Caption
os - Alias not found.


    at y (C:\Users\Chet\Documents\theProject\amplify-next-template\node_modules\envinfo\dist\envinfo.js:1:130041)
    at e.exports.sync (C:\Users\Chet\Documents\theProject\amplify-next-template\node_modules\envinfo\dist\envinfo.js:1:131910)
    at e.exports (C:\Users\Chet\Documents\theProject\amplify-next-template\node_modules\envinfo\dist\envinfo.js:1:128247)
    at e.exports (C:\Users\Chet\Documents\theProject\amplify-next-template\node_modules\envinfo\dist\envinfo.js:1:107151)
    at C:\Users\Chet\Documents\theProject\amplify-next-template\node_modules\envinfo\dist\envinfo.js:1:27846
    at async Promise.all (index 0)
    at async EnvironmentInfoProvider.getEnvInfo (file:///C:/Users/Chet/Documents/theProject/amplify-next-template/node_modules/@aws-amplify/backend-cli/lib/info/env_info_provider.js:12:22)
    at async Object.handler (file:///C:/Users/Chet/Documents/theProject/amplify-next-template/node_modules/@aws-amplify/backend-cli/lib/commands/info/info_command.js:30:33)
```

### Describe the bug

`npx ampx info` fails to generate any information on the environment. Above I've shown the command run with `--debug` included, but it fails in the same way without `--debug` included.

### Reproduction steps

Environment:
I am using Windows 10 version 19045.5247. Please inform me what other information on the environment is relevant. 

Reproduction:
1. Clone the repository. I used the one from the link below. Follow instructions for "Create repository from template".
  https://docs.amplify.aws/nextjs/start/quickstart/nextjs-app-router-client-components/#1-create-the-repository
  You can also clone the repo used in bug demonstration. For me the result is the same:
  https://github.com/Ao1K/amplify-next-template
2. Open powershell. `cd` to the repo and run `npm install`
 Aside: installing dependencies through `npm install` warns of 3 vulnerabilities. Running or not running `npm audit fix --force` does not resolve the issue with `npx ampx info`.
4. Run `npx ampx info --debug`.

**Comment by Ao1K** [comment]
Thanks @ykethan. Yeah, still occurs with the cmd terminal. It fails in the same exact way, according to `--debug`. 

Other commands work. I'm able to run and use `npx ampx sandbox` and `npx ampx generate outputs`.

**Comment by ykethan** [comment]
Hey @Ao1K, thank you for the information. On digging into this, the issue appears to be similar to https://github.com/tabrindle/envinfo/issues/213
From the issue it appears [WMIC](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmic) utility is deprecated on win 10 and 11 that is currently raising this message.

Marking as bug for tracking this behavior.
