### ISSUE TITLE
`npx amplify generate config --stack doesnotexist` prints help, errors with stack trace

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#281]
```
projects/aws-amplify/myproject with 🅰 (us-east-1) 
➜  npx amplify generate config --stack doesnotexist
amplify generate config

Generates client config

Stack identifier
  --stack  A stack name that contains an Amplify backend                [string]

Project identifier
  --appId   The Amplify App ID of the project                           [string]
  --branch  A git branch of the Amplify project                         [string]

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
  --format   The format which the configuration should be exported into.
                                          [string] [choices: "js", "json", "ts"]
  --out      A path to directory where config is written. If not provided defaul
             ts to current process working directory.                   [string]

CloudFormationServiceException [ValidationError]: Stack with id doesnotexist does not exist
    at throwDefaultError (/Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_GetTemplateSummaryCommandError (/Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@aws-sdk/client-cloudformation/dist-cjs/protocols/Aws_query.js:2119:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@aws-sdk/client-cloudformation/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@aws-sdk/client-cloudformation/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async StackMetadataBackendOutputRetrievalStrategy.fetchBackendOutput (file:///Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@aws-amplify/client-config/lib/stack_metadata_output_retrieval_strategy.js:25:33)
    at async UnifiedClientConfigGenerator.generateClientConfig (file:///Users/josefai/Documents/projects/aws-amplify/myproject/node_modules/@aws-amplify/client-config/lib/unified_client_config_generator.js:21:64) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '11cf7256-2609-4463-887d-3af6f894085e',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'ValidationError'
}
```

Instead, this should error without the stack trace and help:

```
projects/aws-amplify/myproject with 🅰 (us-east-1) 
➜  npx amplify generate config --stack doesnotexist
Error: Stack with id "doesnotexist" does not exist
```

**Comment by josefaidt** [comment]
this is now resolved, closing

```
➜  npx amplify generate config --stack doesnotexist


amplify generate config

Generates client config

Stack identifier
  --stack  A stack name that contains an Amplify backend                [string]

Project identifier
  --app-id  The Amplify App ID of the project                           [string]
  --branch  A git branch of the Amplify project                         [string]

Options:
  --help     Show help                                                 [boolean]
  --profile  An AWS profile name.                                       [string]
  --format   The format which the configuration should be exported into.
                  [string] [choices: "mjs", "json", "json-mobile", "ts", "dart"]
  --out-dir  A path to directory where config is written. If not provided defaul
             ts to current process working directory.                   [string]


ValidationError: Stack with id doesnotexist does not exist
```
