### ISSUE TITLE
`npx amplify generate config --branch test` prints help and stack trace

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#283]
```
npx amplify generate config --branch dasdff
amplify generate config

Generates client config

Stack identifier
  --stack  A stack name that contains an Amplify backend                [string]

Project identifier
  --appId   The Amplify App ID of the project                           [string]
  --branch  A git branch of the Amplify project                         [string]

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
  --format   The format which the configuration should be exported into.
                                          [string] [choices: "js", "json", "ts"]
  --out      A path to directory where config is written. If not provided defaul
             ts to current process working directory.                   [string]

Error: No apps found with name samsara in region us-east-1
    at AppNameAndBranchMainStackNameResolver.resolveMainStackName (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/client-config/lib/stack-name-resolvers/app_name_and_branch_main_stack_name_resolver.js:27:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StackMetadataBackendOutputRetrievalStrategy.fetchBackendOutput (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/client-config/lib/stack_metadata_output_retrieval_strategy.js:23:27)
    at async UnifiedClientConfigGenerator.generateClientConfig (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/client-config/lib/unified_client_config_generator.js:21:64)
    at async generateClientConfigToFile (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/client-config/lib/generate_client_config_to_file.js:8:26)
    at async ClientConfigGeneratorAdapter.generateClientConfigToFile (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/backend-cli/lib/commands/generate/config/client_config_generator_adapter.js:24:9)
    at async Object.handler (file:///Users/ykethan/Documents/ampapps/samsara/node_modules/@aws-amplify/backend-cli/lib/commands/generate/config/generate_config_command.js:47:9)

```

**Comment by ykethan** [comment]
update: this no longer prints the stack trace but does still print the help command
