### ISSUE TITLE
ctrl+c on the `npx amplify sandbox` exit prompt crashes with stack trace

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#321]
1. `npx amplify sandbox`
2. ctrl+c
3. ctrl+c
4. observe error

```
[Sandbox] Watching for file changes...
^C[Sandbox] Shutting down
? Would you like to delete all the resources in your sandbox environment (This cannot be undone)? 
(y/N)
file:///Users/josefai/Documents/projects/aws-amplify/tmp-samsara-cli/examples/next.js/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:36
                    reject(new Error(`User force closed the prompt with ${code} ${signal}`));
                           ^

Error: User force closed the prompt with 0 null
    at file:///Users/josefai/Documents/projects/aws-amplify/tmp-samsara-cli/examples/next.js/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:36:28
    at Emitter.emit (file:///Users/josefai/Documents/projects/aws-amplify/tmp-samsara-cli/examples/next.js/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:67:19)
    at #processEmit (file:///Users/josefai/Documents/projects/aws-amplify/tmp-samsara-cli/examples/next.js/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:236:27)
    at #process.emit (file:///Users/josefai/Documents/projects/aws-amplify/tmp-samsara-cli/examples/next.js/node_modules/@inquirer/core/node_modules/signal-exit/dist/mjs/index.js:187:37)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by josefaidt** [comment]
this is resolved
