### ISSUE TITLE
Add test that explores stack/resource naming constraints.

### ISSUE THREAD

**Issue by sobolk** [aws-amplify/amplify-backend#617]
We should add a test (likely e2e test) that deploys a gen2 that has as many resources as possible and uses branch/backendidentifier namings that go up to lenght boundary.

This is follow up from https://github.com/aws-amplify/amplify-backend/pull/594

And from bug report:

```
at Module.load (node:internal/modules/cjs/loader:1081:32)
at Object.S (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/tsx/dist/cjs/index.cjs:1:1250)
at Module._compile (node:internal/modules/cjs/loader:1218:14)
at Object.<anonymous> (/codebuild/output/src2394746949/src/amplify-gen2-private-2/amplify/backend.ts:6:36)
at import_resource (/codebuild/output/src2394746949/src/amplify-gen2-private-2/amplify/backend.ts:6:1)
at Backend (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/@aws-amplify/backend/src/backend.ts:35:53)
at createDefaultStack (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/@aws-amplify/backend/src/default_stack_factory.ts:13:27)
at ProjectEnvironmentMainStackCreator.getOrCreateMainStack (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/@aws-amplify/backend/src/project_environment_main_stack_creator.ts:28:24)
at AmplifyStack (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/@aws-amplify/backend/src/engine/amplify_stack.ts:6:7)
at Stack (/codebuild/output/src2394746949/src/amplify-gen2-private-2/node_modules/aws-cdk-lib/core/lib/stack.js:1:4798)
Error: Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got 'amplify-d3p4rt0vxj5bat-feature--my.feature_.is._awesome_-1'
```

```
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>1 validation error detected: Value 'amplify-d3p4rt0vxj5bat-feature/my.feature_.is._awesome_-1' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*</Message>
  </Error>
  <RequestId>a040ae88-8a23-4edb-a73a-26d15a469257</RequestId>
</ErrorResponse>
```

**Comment by sobolk** [comment]
The mechanism to enforce stack name within limit has been encoded into component that maps backend indentifier into stack name.
