### ISSUE TITLE
running without package manager throws `Error: npm_config_user_agent is undefined`

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#983]
### Environment information

```plain text
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 148.31 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - ~/.local/share/nvm/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.local/share/nvm/v18.18.0/bin/npm
    pnpm: 7.26.2 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: Not Found
    @aws-amplify/backend-cli: Not Found
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: Not Found
```

### Description

for example when running without a package manager throws the following
```
node /amplify-backend/packages/create-amplify/lib/create_amplify.js
? Where should we create your project? ./tets1
file:///amplify-backend/packages/cli-core/lib/package-manager-controller/package_manager_controller_factory.js:43
            throw new Error('npm_config_user_agent is undefined');
                  ^

Error: npm_config_user_agent is undefined
    at PackageManagerControllerFactory.getPackageManagerName (file:///amplify-backend/packages/cli-core/lib/package-manager-controller/package_manager_controller_factory.js:43:19)
    at PackageManagerControllerFactory.getPackageManagerController (file:///amplify-backend/packages/cli-core/lib/package-manager-controller/package_manager_controller_factory.js:23:41)
    at file:///amplify-backend/packages/create-amplify/lib/create_amplify.js:17:66
```

workaround: `export npm_config_user_agent=npm`

**Comment by 0618** [comment]
Related to https://github.com/aws-amplify/amplify-backend/issues/983

**Comment by ykethan** [comment]
Closing as this is an unsupported use case
