### ISSUE TITLE
using yarn to create app fails

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#997]
### Environment information

```plain text
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 174.28 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - ~/.local/share/nvm/v18.18.0/bin/node
    Yarn: 2.4.2 - ~/.local/share/nvm/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.local/share/nvm/v18.18.0/bin/npm
    pnpm: 7.26.2 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: Not Found
    @aws-amplify/backend-cli: Not Found
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: Not Found
```

### Description

<img width="1133" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/4153ffc2-3899-4c2b-83f0-9571e4c03a7a">

-----
yarn 3.6.4 works fine for create

but 

```
 yarn amplify --help
/Users/ykethan/Documents/ampapps/vuw/test2/.pnp.cjs:20534
      Error.captureStackTrace(firstError);
            ^

Error: @aws-amplify/backend-output-schemas tried to access zod (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: zod
Required by: @aws-amplify/backend-output-schemas@virtual:63635f83339afa8c1701362d467aa0bd7877c665d1531049950123f03f716abbd29e0a17b3104e0e706072180584607dd03e39819df722a6e12f57a2867a552e#npm:0.6.0 (via /Users/ykethan/Documents/ampapps/vuw/test2/.yarn/__virtual__/@aws-amplify-backend-output-schemas-virtual-017b091311/0/cache/@aws-amplify-backend-output-schemas-npm-0.6.0-511d7b1308-bf4e5c2db9.zip/node_modules/@aws-amplify/backend-output-schemas/lib/)

Ancestor breaking the chain: @aws-amplify/auth-construct-alpha@virtual:7881ac092eb87312d473431aaf9de8c79c1c3f9d13d1ece015f23069e046612189867459ee54ce793f7a246abc6d6a71dd8d8ecc5f924e5da8b26e66b6ea84c4#npm:0.5.5
Ancestor breaking the chain: @aws-amplify/backend@virtual:70feb6df389605cc9327773928002868e9bc322c702c0fb4430bed37f57b9b8e6edc818f3f98cb0eff81a5276651c025b5c3d836dbadecc498985808b6a23149#npm:0.11.0
Ancestor breaking the chain: @aws-amplify/backend-data@virtual:b0a55ad17795f8e44a95724c33322f200a243c6eb523f82b3466e90c78ac7073a15e9aa7085f4f8fec2c7ecd1f2475c60d5203945cd7c52573cd20595a8a6397#npm:0.9.6
Ancestor breaking the chain: @aws-amplify/backend-output-storage@virtual:b0a55ad17795f8e44a95724c33322f200a243c6eb523f82b3466e90c78ac7073a15e9aa7085f4f8fec2c7ecd1f2475c60d5203945cd7c52573cd20595a8a6397#npm:0.3.0
Ancestor breaking the chain: @aws-amplify/backend-storage@virtual:b0a55ad17795f8e44a95724c33322f200a243c6eb523f82b3466e90c78ac7073a15e9aa7085f4f8fec2c7ecd1f2475c60d5203945cd7c52573cd20595a8a6397#npm:0.5.0
Ancestor breaking the chain: @aws-amplify/model-generator@npm:0.4.0


Require stack:
- /Users/ykethan/Documents/ampapps/vuw/test2/.yarn/__virtual__/@aws-amplify-backend-output-schemas-virtual-017b091311/0/cache/@aws-amplify-backend-output-schemas-npm-0.6.0-511d7b1308-bf4e5c2db9.zip/node_modules/@aws-amplify/backend-output-schemas/lib/index.js
    at require$$0.Module._resolveFilename (/Users/ykethan/Documents/ampapps/vuw/test2/.pnp.cjs:20534:13)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at require$$0.Module._load (/Users/ykethan/Documents/ampapps/vuw/test2/.pnp.cjs:20423:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/ykethan/Documents/ampapps/vuw/test2/.yarn/__virtual__/@aws-amplify-backend-output-schemas-virtual-017b091311/0/cache/@aws-amplify-backend-output-schemas-npm-0.6.0-511d7b1308-bf4e5c2db9.zip/node_modules/@aws-amplify/backend-output-schemas/lib/index.js:18:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (/Users/ykethan/Documents/ampapps/vuw/test2/.pnp.cjs:20578:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

**Comment by josefaidt** [comment]
Marking as a bug

**Comment by 0618** [comment]
Hey @ykethan , I was not able to reproduce the bug. Please make sure to install yarn latest on your local https://yarnpkg.com/getting-started/install

**Comment by 0618** [comment]
We don't support plug&play, so please the following commands to setup environment for yarn2+

```
yarn -v
corepack enable
yarn init -2
yarn cache clean --all &&
yarn config set unsafeHttpWhitelist localhost &&
yarn config set npmRegistryServer http://localhost:4873 &&
yarn config set nodeLinker node-modules 
yarn -v
```

**Comment by ykethan** [comment]
The issue was the folder a level up contained `.yarn` and `yarnrc` which were hidden and causing this behavior. removing the them and retrying fixed this. 
closing the issue
