### ISSUE TITLE
Can't perform VPC lookups from stacks created within amplify gen 2

### ISSUE THREAD

**Issue by malaquf** [aws-amplify/amplify-backend#999]
### Environment information

```plain text
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 16.72 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.1 - /opt/homebrew/bin/pnpm
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.10.3 => 0.10.3 
    @aws-amplify/backend-cli: ^0.10.0 => 0.10.0 
    aws-amplify: Not Found
    aws-cdk: Not Found
    aws-cdk-lib: ^2.126.0 => 2.126.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

Stacks created from Backend can't perform lookups to resources due to missing env definition (account id and region).

Example:
```
import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource.ts';
import { data } from './data/resource.ts';

const backend = defineBackend({
   auth,
   data,
})

const stack = backend.createStack('ChatCompletionStack')
const vpc = Vpc.fromLookup(stack, 'Vpc', {isDefault: true})
```

**Comment by josefaidt** [comment]
Hey @malaquf :wave: thanks for raising this! What's the error you're seeing?

**Comment by malaquf** [comment]
Hi @josefaidt,

Here you go:
```
Error: Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
    at ContextProvider.getValue (/app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.126.0_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/context-provider.js:2:562)
    at Vpc.fromLookup (/app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.126.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:9203)
...
```

**Comment by josefaidt** [comment]
Hey @malaquf :wave: upon further investigation this will not be addressed due to how Stacks are structured and how the AWS account and region are resolved using [CDK tokens] that resolve the account and region at runtime. There's a small callout on the method in the CDK docs that adds some detail:

> Calling this method will lead to a lookup when the CDK CLI is executed. You can therefore not use any values that will only be available at CloudFormation execution time (i.e., Tokens).

Implementing something to allow you to specify an account ID and region would likely motivate you to use environment variables to manage account and region references across branches and sandboxes. Instead, we suggest pivoting to use environment variables to reference VPC attributes and use [`Vpc.fromVpcAttributes()`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Vpc.html#static-fromwbrvpcwbrattributesscope-id-attrs) to reference your existing VPC.

Please let me know if this works for you!

**Comment by malaquf** [comment]
Hi @josefaidt,
Sorry for the delay. Unfortunately, the import by attributes also didn't work, for a different reason.
In this case, the imported vpc finds no subnets and it then fails during a NodeJS function creation, for eg.

```
Error: There are no 'Private' subnet groups in this VPC. Available types: 
    at ImportedVpc.selectSubnetObjectsByType (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:6197)
    at ImportedVpc.selectSubnetObjects (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:4915)
    at ImportedVpc.selectSubnets (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:2603)
    at NodejsFunction.configureVpc (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:23333)
    at new Function (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:12479)
    at new NodejsFunction (/Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/node_modules/.pnpm/aws-cdk-lib@2.128.0_constructs@10.3.0/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:1669)
    at createChatCompletionFunction (file:///Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/amplify/custom/chat-completion/chat-completion-stack.ts:1:5117)
    at createChatCompletionStack (file:///Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/amplify/custom/chat-completion/chat-completion-stack.ts:1:1344)
    at file:///Users/felipe/Documents/dev/repos/travel-app-amplify-gen2/backend/amplify/backend.ts:1:253
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
```
Please note that in my TF script I'm also including "aws-cdk:subnet-type" = "Private" tag, as I expect CDK will look for it.

I've also tried to manually define the vpc, subnet and route table attributes in cdk.context.json but also without success.

**Comment by malaquf** [comment]
Alright, just for others that stumble into this, I automated the vpc attributes by [generating](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate) a json out of my terragrunt script and imported it in my cdk stack. 

eg.:
```
generate "vpc" {
  path      = "../../../vpc.json"
  if_exists = "overwrite"
  disable_signature = true
  contents = <<-EOF
    {
      "key": "value"
    }
    EOF
}
```

Thanks!

**Comment by josefaidt** [comment]
Hey @malaquf thanks for confirming! I've pivoted this to a feature-request for the change in behavior to enable supplying CDK account and region, however will close this in favor of using `vpc.fromVpcAttributes`

**Comment by josefaidt** [comment]
reviving this issue to track support for vpc lookups, ease of use within Amplify backend projects
